#############################################################################
# Makefile for building: BigBrother.app/Contents/MacOS/BigBrother
# Generated by qmake (3.1) (Qt 6.2.1)
# Project:  BigBrother.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile BigBrother.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=11 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=11 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/opt/opencv/include/opencv4 -I/usr/local/Cellar/libtensorflow/2.7.0/include -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/share/qt/mkspecs/macx-clang -F/usr/local/lib
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = BigBrother1.0.0
DISTDIR = ~/.tmp/BigBrother1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=11 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/usr/local/lib
LIBS          = $(SUBLIBS) -F/usr/local/lib -L/usr/local/opt/opencv/lib -lopencv_gapi -lopencv_stitching -lopencv_alphamat -lopencv_aruco -lopencv_barcode -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hfs -lopencv_img_hash -lopencv_intensity_transform -lopencv_line_descriptor -lopencv_mcc -lopencv_quality -lopencv_rapid -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_sfm -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_optflow -lopencv_surface_matching -lopencv_tracking -lopencv_highgui -lopencv_datasets -lopencv_text -lopencv_plot -lopencv_videostab -lopencv_videoio -lopencv_viz -lopencv_wechat_qrcode -lopencv_xfeatures2d -lopencv_shape -lopencv_ml -lopencv_ximgproc -lopencv_video -lopencv_dnn -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core -L/usr/local/Cellar/libtensorflow/2.7.0/lib -ltensorflow -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		MaskDetector.cpp \
		Face.cpp \
		FaceDetector.cpp \
		Report.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		MaskDetector.o \
		Face.o \
		FaceDetector.o \
		Report.o \
		moc_mainwindow.o
DIST          = /usr/local/share/qt/mkspecs/features/spec_pre.prf \
		/usr/local/share/qt/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/clang-mac.conf \
		/usr/local/share/qt/mkspecs/qconfig.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/share/qt/mkspecs/features/qt_functions.prf \
		/usr/local/share/qt/mkspecs/features/qt_config.prf \
		/usr/local/share/qt/mkspecs/macx-clang/qmake.conf \
		/usr/local/share/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/local/share/qt/mkspecs/features/mac/sdk.prf \
		/usr/local/share/qt/mkspecs/features/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/mac/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/resolve_config.prf \
		/usr/local/share/qt/mkspecs/features/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/objective_c.prf \
		/usr/local/share/qt/mkspecs/features/link_pkgconfig.prf \
		/usr/local/share/qt/mkspecs/features/mac/mac.prf \
		/usr/local/share/qt/mkspecs/features/warn_on.prf \
		/usr/local/share/qt/mkspecs/features/qt.prf \
		/usr/local/share/qt/mkspecs/features/resources_functions.prf \
		/usr/local/share/qt/mkspecs/features/resources.prf \
		/usr/local/share/qt/mkspecs/features/moc.prf \
		/usr/local/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/local/share/qt/mkspecs/features/uic.prf \
		/usr/local/share/qt/mkspecs/features/unix/thread.prf \
		/usr/local/share/qt/mkspecs/features/qmake_use.prf \
		/usr/local/share/qt/mkspecs/features/file_copies.prf \
		/usr/local/share/qt/mkspecs/features/mac/rez.prf \
		/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/share/qt/mkspecs/features/testcase_targets.prf \
		/usr/local/share/qt/mkspecs/features/exceptions.prf \
		/usr/local/share/qt/mkspecs/features/yacc.prf \
		/usr/local/share/qt/mkspecs/features/lex.prf \
		BigBrother.pro environment.hpp \
		opencv.hpp \
		MaskDetector.hpp \
		mainwindow.hpp \
		FaceDetector.hpp \
		Face.hpp \
		Report.hpp main.cpp \
		mainwindow.cpp \
		MaskDetector.cpp \
		Face.cpp \
		FaceDetector.cpp \
		Report.cpp
QMAKE_TARGET  = BigBrother
DESTDIR       = 
TARGET        = BigBrother.app/Contents/MacOS/BigBrother

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 11.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = ~/.qmake.stash
EXPORT_VALID_ARCHS = x86_64
EXPORT_DEFAULT_ARCHS = x86_64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = ~/BigBrother.pro


include /usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

BigBrother.app/Contents/MacOS/BigBrother:  $(OBJECTS)  
	@test -d BigBrother.app/Contents/MacOS/ || mkdir -p BigBrother.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BigBrother.pro /usr/local/share/qt/mkspecs/macx-clang/qmake.conf /usr/local/share/qt/mkspecs/features/spec_pre.prf \
		/usr/local/share/qt/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/clang-mac.conf \
		/usr/local/share/qt/mkspecs/qconfig.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/share/qt/mkspecs/features/qt_functions.prf \
		/usr/local/share/qt/mkspecs/features/qt_config.prf \
		/usr/local/share/qt/mkspecs/macx-clang/qmake.conf \
		/usr/local/share/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/local/share/qt/mkspecs/features/mac/sdk.prf \
		/usr/local/share/qt/mkspecs/features/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/mac/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/resolve_config.prf \
		/usr/local/share/qt/mkspecs/features/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/objective_c.prf \
		/usr/local/share/qt/mkspecs/features/link_pkgconfig.prf \
		/usr/local/share/qt/mkspecs/features/mac/mac.prf \
		/usr/local/share/qt/mkspecs/features/warn_on.prf \
		/usr/local/share/qt/mkspecs/features/qt.prf \
		/usr/local/share/qt/mkspecs/features/resources_functions.prf \
		/usr/local/share/qt/mkspecs/features/resources.prf \
		/usr/local/share/qt/mkspecs/features/moc.prf \
		/usr/local/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/local/share/qt/mkspecs/features/uic.prf \
		/usr/local/share/qt/mkspecs/features/unix/thread.prf \
		/usr/local/share/qt/mkspecs/features/qmake_use.prf \
		/usr/local/share/qt/mkspecs/features/file_copies.prf \
		/usr/local/share/qt/mkspecs/features/mac/rez.prf \
		/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/share/qt/mkspecs/features/testcase_targets.prf \
		/usr/local/share/qt/mkspecs/features/exceptions.prf \
		/usr/local/share/qt/mkspecs/features/yacc.prf \
		/usr/local/share/qt/mkspecs/features/lex.prf \
		BigBrother.pro \
		/usr/local/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/usr/local/lib/QtGui.framework/Resources/QtGui.prl \
		/usr/local/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile BigBrother.pro
/usr/local/share/qt/mkspecs/features/spec_pre.prf:
/usr/local/share/qt/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/common/clang-mac.conf:
/usr/local/share/qt/mkspecs/qconfig.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_charts.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_coap.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_coap_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_help.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_linguist.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_linguist_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opcua.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opcua_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_tools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webview.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/share/qt/mkspecs/features/qt_functions.prf:
/usr/local/share/qt/mkspecs/features/qt_config.prf:
/usr/local/share/qt/mkspecs/macx-clang/qmake.conf:
/usr/local/share/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/local/share/qt/mkspecs/features/mac/sdk.prf:
/usr/local/share/qt/mkspecs/features/toolchain.prf:
/usr/local/share/qt/mkspecs/features/mac/toolchain.prf:
/usr/local/share/qt/mkspecs/features/default_pre.prf:
/usr/local/share/qt/mkspecs/features/mac/default_pre.prf:
/usr/local/share/qt/mkspecs/features/resolve_config.prf:
/usr/local/share/qt/mkspecs/features/default_post.prf:
/usr/local/share/qt/mkspecs/features/mac/default_post.prf:
/usr/local/share/qt/mkspecs/features/mac/objective_c.prf:
/usr/local/share/qt/mkspecs/features/link_pkgconfig.prf:
/usr/local/share/qt/mkspecs/features/mac/mac.prf:
/usr/local/share/qt/mkspecs/features/warn_on.prf:
/usr/local/share/qt/mkspecs/features/qt.prf:
/usr/local/share/qt/mkspecs/features/resources_functions.prf:
/usr/local/share/qt/mkspecs/features/resources.prf:
/usr/local/share/qt/mkspecs/features/moc.prf:
/usr/local/share/qt/mkspecs/features/unix/opengl.prf:
/usr/local/share/qt/mkspecs/features/uic.prf:
/usr/local/share/qt/mkspecs/features/unix/thread.prf:
/usr/local/share/qt/mkspecs/features/qmake_use.prf:
/usr/local/share/qt/mkspecs/features/file_copies.prf:
/usr/local/share/qt/mkspecs/features/mac/rez.prf:
/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/share/qt/mkspecs/features/testcase_targets.prf:
/usr/local/share/qt/mkspecs/features/exceptions.prf:
/usr/local/share/qt/mkspecs/features/yacc.prf:
/usr/local/share/qt/mkspecs/features/lex.prf:
BigBrother.pro:
/usr/local/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/usr/local/lib/QtGui.framework/Resources/QtGui.prl:
/usr/local/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile BigBrother.pro

qmake_all: FORCE

BigBrother.app/Contents/PkgInfo: 
	@test -d BigBrother.app/Contents || mkdir -p BigBrother.app/Contents
	@$(DEL_FILE) BigBrother.app/Contents/PkgInfo
	@echo "APPL????" > BigBrother.app/Contents/PkgInfo
BigBrother.app/Contents/Resources/empty.lproj: 
	@test -d BigBrother.app/Contents/Resources || mkdir -p BigBrother.app/Contents/Resources
	@touch BigBrother.app/Contents/Resources/empty.lproj
	
BigBrother.app/Contents/Info.plist: 
	@test -d BigBrother.app/Contents || mkdir -p BigBrother.app/Contents
	@$(DEL_FILE) BigBrother.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.3305.BigBrother,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.3305.BigBrother,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},11,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,BigBrother,g" -e "s,@LIBRARY@,BigBrother,g" -e "s,\$${EXECUTABLE_NAME},BigBrother,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /usr/local/share/qt/mkspecs/macx-clang/Info.plist.app >BigBrother.app/Contents/Info.plist

all: Makefile \
		BigBrother.app/Contents/PkgInfo \
		BigBrother.app/Contents/Resources/empty.lproj \
		BigBrother.app/Contents/Info.plist BigBrother.app/Contents/MacOS/BigBrother

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/share/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents environment.hpp opencv.hpp MaskDetector.hpp mainwindow.hpp FaceDetector.hpp Face.hpp Report.hpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp MaskDetector.cpp Face.cpp FaceDetector.cpp Report.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r BigBrother.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/share/qt/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/local/share/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.hpp \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGraphicsView \
		/usr/local/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/lib/QtWidgets.framework/Headers/QStackedWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QRadioButton \
		/usr/local/lib/QtWidgets.framework/Headers/qradiobutton.h \
		/usr/local/lib/QtWidgets.framework/Headers/QListWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qlistwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/lib/QtCore.framework/Headers/QTimer \
		/usr/local/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/lib/QtWidgets.framework/Headers/QSlider \
		/usr/local/lib/QtWidgets.framework/Headers/qslider.h \
		/usr/local/lib/QtWidgets.framework/Headers/QDoubleSpinBox \
		/usr/local/lib/QtWidgets.framework/Headers/qspinbox.h \
		opencv.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvdef.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/version.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/hal/interface.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/hal/msa_macros.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/base.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/check.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/traits.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/matx.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/saturate.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/types.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/mat.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/persistence.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/operations.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utility.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utils/instrumentation.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utils/tls.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/optim.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/ovx.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video/tracking.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgproc.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgproc/segmentation.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video/background_segm.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/videoio.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/highgui.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/objdetect.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgcodecs/imgcodecs.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/calib3d.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/features2d.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/miniflann.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/defines.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/config.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/affine.hpp \
		environment.hpp \
		Face.hpp \
		MaskDetector.hpp \
		cppflow/cppflow.h \
		cppflow/tensor.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_tensor.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/c_api_macros.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_datatype.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_status.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/eager/c_api.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/c_api.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_attrtype.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_tstring.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/core/platform/ctstring.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/core/platform/ctstring_internal.h \
		cppflow/context.h \
		cppflow/datatype.h \
		cppflow/model.h \
		cppflow/defer.h \
		cppflow/raw_ops.h \
		cppflow/ops.h \
		FaceDetector.hpp \
		Report.hpp \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include ~/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/usr/local/opt/opencv/include/opencv4 -I/usr/local/Cellar/libtensorflow/2.7.0/include -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.5/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib mainwindow.hpp -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.hpp \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGraphicsView \
		/usr/local/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/lib/QtWidgets.framework/Headers/QStackedWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QRadioButton \
		/usr/local/lib/QtWidgets.framework/Headers/qradiobutton.h \
		/usr/local/lib/QtWidgets.framework/Headers/QListWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qlistwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/lib/QtCore.framework/Headers/QTimer \
		/usr/local/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/lib/QtWidgets.framework/Headers/QSlider \
		/usr/local/lib/QtWidgets.framework/Headers/qslider.h \
		/usr/local/lib/QtWidgets.framework/Headers/QDoubleSpinBox \
		/usr/local/lib/QtWidgets.framework/Headers/qspinbox.h \
		opencv.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvdef.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/version.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/hal/interface.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/hal/msa_macros.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/base.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/check.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/traits.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/matx.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/saturate.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/types.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/mat.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/persistence.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/operations.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utility.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utils/instrumentation.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utils/tls.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/optim.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/ovx.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video/tracking.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgproc.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgproc/segmentation.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video/background_segm.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/videoio.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/highgui.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/objdetect.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgcodecs/imgcodecs.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/calib3d.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/features2d.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/miniflann.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/defines.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/config.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/affine.hpp \
		environment.hpp \
		Face.hpp \
		MaskDetector.hpp \
		cppflow/cppflow.h \
		cppflow/tensor.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_tensor.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/c_api_macros.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_datatype.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_status.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/eager/c_api.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/c_api.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_attrtype.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_tstring.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/core/platform/ctstring.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/core/platform/ctstring_internal.h \
		cppflow/context.h \
		cppflow/datatype.h \
		cppflow/model.h \
		cppflow/defer.h \
		cppflow/raw_ops.h \
		cppflow/ops.h \
		FaceDetector.hpp \
		Report.hpp \
		/usr/local/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.hpp \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGraphicsView \
		/usr/local/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/lib/QtWidgets.framework/Headers/QStackedWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QRadioButton \
		/usr/local/lib/QtWidgets.framework/Headers/qradiobutton.h \
		/usr/local/lib/QtWidgets.framework/Headers/QListWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qlistwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/lib/QtCore.framework/Headers/QTimer \
		/usr/local/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/lib/QtWidgets.framework/Headers/QSlider \
		/usr/local/lib/QtWidgets.framework/Headers/qslider.h \
		/usr/local/lib/QtWidgets.framework/Headers/QDoubleSpinBox \
		/usr/local/lib/QtWidgets.framework/Headers/qspinbox.h \
		opencv.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvdef.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/version.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/hal/interface.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/hal/msa_macros.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/base.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/check.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/traits.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/matx.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/saturate.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/types.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/mat.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/persistence.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/operations.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utility.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utils/instrumentation.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utils/tls.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/optim.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/ovx.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video/tracking.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgproc.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgproc/segmentation.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video/background_segm.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/videoio.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/highgui.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/objdetect.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgcodecs/imgcodecs.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/calib3d.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/features2d.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/miniflann.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/defines.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/config.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/affine.hpp \
		environment.hpp \
		Face.hpp \
		MaskDetector.hpp \
		cppflow/cppflow.h \
		cppflow/tensor.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_tensor.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/c_api_macros.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_datatype.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_status.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/eager/c_api.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/c_api.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_attrtype.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_tstring.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/core/platform/ctstring.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/core/platform/ctstring_internal.h \
		cppflow/context.h \
		cppflow/datatype.h \
		cppflow/model.h \
		cppflow/defer.h \
		cppflow/raw_ops.h \
		cppflow/ops.h \
		FaceDetector.hpp \
		Report.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

MaskDetector.o: MaskDetector.cpp MaskDetector.hpp \
		cppflow/cppflow.h \
		cppflow/tensor.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_tensor.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/c_api_macros.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_datatype.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_status.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/eager/c_api.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/c_api.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_attrtype.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_tstring.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/core/platform/ctstring.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/core/platform/ctstring_internal.h \
		cppflow/context.h \
		cppflow/datatype.h \
		cppflow/model.h \
		cppflow/defer.h \
		cppflow/raw_ops.h \
		cppflow/ops.h \
		opencv.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvdef.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/version.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/hal/interface.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/hal/msa_macros.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/base.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/check.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/traits.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/matx.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/saturate.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/types.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/mat.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/persistence.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/operations.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utility.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utils/instrumentation.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utils/tls.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/optim.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/ovx.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video/tracking.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgproc.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgproc/segmentation.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video/background_segm.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/videoio.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/highgui.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/objdetect.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgcodecs/imgcodecs.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/calib3d.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/features2d.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/miniflann.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/defines.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/config.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/affine.hpp \
		environment.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MaskDetector.o MaskDetector.cpp

Face.o: Face.cpp Face.hpp \
		opencv.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvdef.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/version.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/hal/interface.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/hal/msa_macros.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/base.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/check.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/traits.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/matx.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/saturate.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/types.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/mat.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/persistence.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/operations.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utility.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utils/instrumentation.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utils/tls.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/optim.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/ovx.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video/tracking.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgproc.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgproc/segmentation.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video/background_segm.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/videoio.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/highgui.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/objdetect.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgcodecs/imgcodecs.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/calib3d.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/features2d.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/miniflann.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/defines.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/config.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/affine.hpp \
		environment.hpp \
		MaskDetector.hpp \
		cppflow/cppflow.h \
		cppflow/tensor.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_tensor.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/c_api_macros.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_datatype.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_status.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/eager/c_api.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/c_api.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_attrtype.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_tstring.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/core/platform/ctstring.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/core/platform/ctstring_internal.h \
		cppflow/context.h \
		cppflow/datatype.h \
		cppflow/model.h \
		cppflow/defer.h \
		cppflow/raw_ops.h \
		cppflow/ops.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Face.o Face.cpp

FaceDetector.o: FaceDetector.cpp FaceDetector.hpp \
		environment.hpp \
		opencv.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvdef.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/version.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/hal/interface.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/hal/msa_macros.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/base.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/check.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/traits.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/matx.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/saturate.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/types.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/mat.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/persistence.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/operations.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utility.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utils/instrumentation.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utils/tls.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/optim.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/ovx.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video/tracking.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgproc.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgproc/segmentation.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video/background_segm.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/videoio.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/highgui.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/objdetect.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgcodecs/imgcodecs.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/calib3d.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/features2d.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/miniflann.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/defines.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/config.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/affine.hpp \
		MaskDetector.hpp \
		cppflow/cppflow.h \
		cppflow/tensor.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_tensor.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/c_api_macros.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_datatype.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_status.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/eager/c_api.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/c_api.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_attrtype.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/c/tf_tstring.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/core/platform/ctstring.h \
		/usr/local/Cellar/libtensorflow/2.7.0/include/tensorflow/core/platform/ctstring_internal.h \
		cppflow/context.h \
		cppflow/datatype.h \
		cppflow/model.h \
		cppflow/defer.h \
		cppflow/raw_ops.h \
		cppflow/ops.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FaceDetector.o FaceDetector.cpp

Report.o: Report.cpp Report.hpp \
		environment.hpp \
		opencv.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvdef.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/version.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/hal/interface.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/hal/msa_macros.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/base.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/check.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/traits.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/matx.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/saturate.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/types.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/mat.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/persistence.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/operations.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utility.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utils/instrumentation.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/utils/tls.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/optim.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/ovx.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video/tracking.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgproc.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgproc/segmentation.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/video/background_segm.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/videoio.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/highgui.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/objdetect.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/imgcodecs/imgcodecs.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/calib3d.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/features2d.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/miniflann.hpp \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/defines.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/flann/config.h \
		/usr/local/opt/opencv/include/opencv4/opencv2/core/affine.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Report.o Report.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

